### ISSUE TITLE
ROS stuck on loading controllers

### ISSUE THREAD

**Issue by fraiori0** [BRAIR-Education/line_tracking_race#1]
To reproduce:

1. Clone package in /src of catkin workspace
2. Build
3. Source the setup.bash
4. $ roslaunch line_tracking_race car_world.launch

Gazebo should correctly open and show the car model (mid air). If The simulation is played, the car should fall to the ground, but the terminal get stuck on loading controllers.

I already tried with another package, and there the controller_manager correctly loads the controllers

It may be an issue related to the XACRO/YAML, but I cannot find it

**Comment by Elektron97** [comment]
They have called "spawn_model" node without running "gazebo_ros " node as Construct IDE runs Gazebo in the beginning itself. Normal way is to "inlcude empty_world.launch" file before calling spawn_model node. Have a look here: [Gazebo not starting on loading urdf](https://answers.ros.org/question/276753/urdf-spawn-into-gazebo-world-error/) . As, [@Weasfas](https://answers.ros.org/users/34184/weasfas/) has clearly explained that controller_manager requires an interface provided by Gazebo or a real-robot to load controllers. So, here Gazebo itself was not getting started and thus controller manager was not able to load controllers. Solution: (worked for me) : Simply added <include file="$(find gazebo_ros)/launch/empty_world.launch"/>before <group ns="/mrm"> tag ! Hope It helps

**Comment by Elektron97** [comment]
Solved this issue simply putting the plugin `gazebo_ros_control` inside the ` <gazebo>` tag.
